# Generated by Django 2.2.7 on 2019-12-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('Telefon', models.CharField(max_length=9)),
                ('Kod_pocztowy', models.TextField(max_length=6)),
                ('Adres', models.CharField(max_length=45)),
                ('Miasto', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('Pesel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Zlecenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zlecenie', models.TextField(max_length=300)),
                ('Zaplacone', models.BooleanField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alto.Klient')),
            ],
        ),
        migrations.CreateModel(
            name='Obecnosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dzien', models.DateTimeField(auto_now_add=True)),
                ('Obecnosc', models.BooleanField()),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alto.Personel')),
            ],
        ),
        migrations.CreateModel(
            name='Dane_firmy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nip', models.CharField(max_length=11)),
                ('Nazwa_firmy', models.CharField(max_length=45)),
                ('Kod_pocztowy', models.TextField(max_length=6)),
                ('Adres', models.CharField(max_length=45)),
                ('Miasto', models.CharField(max_length=45)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alto.Klient')),
            ],
        ),
    ]
