# Generated by Django 2.2.7 on 2019-12-12 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alto', '0002_auto_20191205_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane_firmy',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Firma', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
