# Generated by Django 2.2.7 on 2019-12-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alto', '0003_dane_firmy_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='Kod_pocztowy',
            field=models.CharField(max_length=6),
        ),
    ]
